format = """
$directory\
$git_branch\
$git_status\
$fill\
$go\
$python\
$lua\
$nodejs\
$golang\
$rust\
$php\
$jobs\
$cmd_duration\
$line_break\
$character"""


palette = 'catppuccin_mocha'


# [fill]
# symbol = ' '


[directory]
# style = 'bold fg:dark_blue'
# format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[cmd_duration]
min_time = 100

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[lua]
symbol = ' '
format = '[${symbol}](blue)'

[golang]
symbol = ' '
format = '[${symbol}](blue)'

[nodejs]
symbol = ' '
format = '[${symbol}](green)'

[php]
format = '[${symbol}](blue)'


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
